[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'active': {
      \   'left': [['mode', 'paste'], ['readonly', 'filename', 'modified']],
      \   'right': [['lineinfo'], ['percent'], ['fileformat', 'fileencoding', 'filetype']]
      \ },
      \ 'component_function': {
      \   'filename': 'VimrcLightlineFilename',
      \   'readonly': 'VimrcLightlineReadonly'
      \ }
      \ }

function! VimrcLightlineReadonly()
  return &readonly ? 'RO' : ''
endfunction

function! VimrcLightlineFilename()
  return empty(expand('%')) ? '[No Name]' : expand('%')
endfunction
'''

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
let g:ale_completion_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_open_list = 0
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_linters = {
      \ 'go': ['gopls'],
      \ 'rust': ['analyzer'],
      \ }
let g:ale_echo_msg_format = '[%linter%] %s'
let g:ale_sign_error = 'E'
let g:ale_sign_warning = 'W'
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']
hook_add = '''
nnoremap <silent> <Leader>f :Files<CR>
nnoremap <silent> <Leader>g :GFiles<CR>
nnoremap <silent> <Leader>b :Buffers<CR>
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
nmap <Leader>c <Plug>(caw:prefix)
vmap <Leader>c <Plug>(caw:prefix)
'''

[[plugins]]
repo = 'kana/vim-altr'
hook_add = '''
nmap <Leader>a <Plug>(altr-forward)
nmap <Leader>b <Plug>(altr-back)
augroup VimAltrCommands
  autocmd!
  autocmd FileType c call altr#define('%.c', '%.h')
  autocmd FileType cpp call altr#define('%.cc', '%.h', '%.c')
  autocmd FileType ruby call altr#define('app/%.rb', 'spec/%_spec.rb')
augroup END
'''

[[plugins]]
repo = 'thinca/vim-visualstar'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = 'vim-scripts/wombat256.vim'
